MagnoliaBakery/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagnoliaBakery.Models;

namespace MagnoliaBakery.Controllers
{
    public class FormController : Controller
    {
        //
        // GET: /Form/

        public ActionResult Comment()
        {
            CommentModel model = new CommentModel();

            return View(model);
        }

        [HttpPost]
        public ActionResult SubmitInfo(CommentModel model)
        {
            TempData["model"] = model;

            return Redirect("/Form/PostedComment");
        }

        public ActionResult PostedComment()
        {
            CommentModel model = TempData["model"] as CommentModel;

            return View(model);
        }
    }
}

MagnoliaBakery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Magnolia Bakery</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Magnolia Bakery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="padding-left:10px;">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Menu", "Menu", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Comment", "Form")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>